[package]
name = "wanco-workspace"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["wanco", "lib-wasi"]
default-members = ["wanco"]

[[bin]]
name = "wanco"
path = "src/main.rs"

#[[lib]]
#name = "lib-wasi"
#path = "src/lib.rs"
