[package]
name = "wanco-workspace"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["wanco", "lib/rust/*"]
default-members = ["wanco", "lib/rust/*"]

[[bin]]
name = "wanco"
path = "src/main.rs"
