[package]
name = "wanco-workspace"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["compiler"]
default-members = ["wanco"]
exclude = ["lib/**/*"]

[[bin]]
name = "wanco"
path = "src/main.rs"
