// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/chkpt.proto
// Protobuf C++ Version: 5.28.2

#include "protobuf/chkpt.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace chkpt {

inline constexpr Value::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::chkpt::Type_Enum >(0)},
        test_oneof_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Value::Value(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ValueDefaultTypeInternal() {}
  union {
    Value _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ValueDefaultTypeInternal _Value_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR Type::Type(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct TypeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TypeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TypeDefaultTypeInternal() {}
  union {
    Type _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TypeDefaultTypeInternal _Type_default_instance_;

inline constexpr Frame::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : locals_{},
        stack_{},
        fn_idx_{0},
        pc_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Frame::Frame(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameDefaultTypeInternal() {}
  union {
    Frame _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameDefaultTypeInternal _Frame_default_instance_;

inline constexpr Checkpoint::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : frames_{},
        globals_{},
        table_{},
        _table_cached_byte_size_{0},
        memory_lz4_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        memory_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Checkpoint::Checkpoint(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CheckpointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckpointDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckpointDefaultTypeInternal() {}
  union {
    Checkpoint _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckpointDefaultTypeInternal _Checkpoint_default_instance_;
}  // namespace chkpt
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_protobuf_2fchkpt_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protobuf_2fchkpt_2eproto = nullptr;
const ::uint32_t
    TableStruct_protobuf_2fchkpt_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chkpt::Type, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chkpt::Value, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::chkpt::Value, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chkpt::Value, _impl_.type_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::chkpt::Value, _impl_.test_oneof_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chkpt::Frame, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chkpt::Frame, _impl_.fn_idx_),
        PROTOBUF_FIELD_OFFSET(::chkpt::Frame, _impl_.pc_),
        PROTOBUF_FIELD_OFFSET(::chkpt::Frame, _impl_.locals_),
        PROTOBUF_FIELD_OFFSET(::chkpt::Frame, _impl_.stack_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chkpt::Checkpoint, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chkpt::Checkpoint, _impl_.frames_),
        PROTOBUF_FIELD_OFFSET(::chkpt::Checkpoint, _impl_.globals_),
        PROTOBUF_FIELD_OFFSET(::chkpt::Checkpoint, _impl_.table_),
        PROTOBUF_FIELD_OFFSET(::chkpt::Checkpoint, _impl_.memory_size_),
        PROTOBUF_FIELD_OFFSET(::chkpt::Checkpoint, _impl_.memory_lz4_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::chkpt::Type)},
        {8, -1, -1, sizeof(::chkpt::Value)},
        {22, -1, -1, sizeof(::chkpt::Frame)},
        {34, -1, -1, sizeof(::chkpt::Checkpoint)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::chkpt::_Type_default_instance_._instance,
    &::chkpt::_Value_default_instance_._instance,
    &::chkpt::_Frame_default_instance_._instance,
    &::chkpt::_Checkpoint_default_instance_._instance,
};
const char descriptor_table_protodef_protobuf_2fchkpt_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024protobuf/chkpt.proto\022\005chkpt\"C\n\004Type\";\n"
    "\004Enum\022\017\n\013UNSPECIFIED\020\000\022\007\n\003I32\020\001\022\007\n\003I64\020\002"
    "\022\007\n\003F32\020\003\022\007\n\003F64\020\004\"q\n\005Value\022\036\n\004type\030\001 \001("
    "\0162\020.chkpt.Type.Enum\022\r\n\003i32\030\002 \001(\005H\000\022\r\n\003i6"
    "4\030\003 \001(\003H\000\022\r\n\003f32\030\004 \001(\002H\000\022\r\n\003f64\030\005 \001(\001H\000B"
    "\014\n\ntest_oneof\"^\n\005Frame\022\016\n\006fn_idx\030\001 \001(\005\022\n"
    "\n\002pc\030\002 \001(\005\022\034\n\006locals\030\003 \003(\0132\014.chkpt.Value"
    "\022\033\n\005stack\030\004 \003(\0132\014.chkpt.Value\"\201\001\n\nCheckp"
    "oint\022\034\n\006frames\030\001 \003(\0132\014.chkpt.Frame\022\035\n\007gl"
    "obals\030\002 \003(\0132\014.chkpt.Value\022\r\n\005table\030\003 \003(\005"
    "\022\023\n\013memory_size\030\004 \001(\005\022\022\n\nmemory_lz4\030\005 \001("
    "\014B\003\370\001\001b\006proto3"
};
static ::absl::once_flag descriptor_table_protobuf_2fchkpt_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protobuf_2fchkpt_2eproto = {
    false,
    false,
    454,
    descriptor_table_protodef_protobuf_2fchkpt_2eproto,
    "protobuf/chkpt.proto",
    &descriptor_table_protobuf_2fchkpt_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_protobuf_2fchkpt_2eproto::offsets,
    file_level_enum_descriptors_protobuf_2fchkpt_2eproto,
    file_level_service_descriptors_protobuf_2fchkpt_2eproto,
};
namespace chkpt {
const ::google::protobuf::EnumDescriptor* Type_Enum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protobuf_2fchkpt_2eproto);
  return file_level_enum_descriptors_protobuf_2fchkpt_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Type_Enum_internal_data_[] = {
    327680u, 0u, };
bool Type_Enum_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Type_Enum Type::UNSPECIFIED;
constexpr Type_Enum Type::I32;
constexpr Type_Enum Type::I64;
constexpr Type_Enum Type::F32;
constexpr Type_Enum Type::F64;
constexpr Type_Enum Type::Enum_MIN;
constexpr Type_Enum Type::Enum_MAX;
constexpr int Type::Enum_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Type::_Internal {
 public:
};

Type::Type(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:chkpt.Type)
}
Type::Type(
    ::google::protobuf::Arena* arena,
    const Type& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Type* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:chkpt.Type)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Type::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_Type_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Type::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<Type>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Type>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Type>(), &Type::ByteSizeLong,
                &Type::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Type, _impl_._cached_size_),
            false,
        },
        &Type::kDescriptorMethods,
        &descriptor_table_protobuf_2fchkpt_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Type::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> Type::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chkpt::Type>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata Type::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Value::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::chkpt::Value, _impl_._oneof_case_);
};

Value::Value(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chkpt.Value)
}
inline PROTOBUF_NDEBUG_INLINE Value::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chkpt::Value& from_msg)
      : test_oneof_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Value::Value(
    ::google::protobuf::Arena* arena,
    const Value& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Value* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;
  switch (test_oneof_case()) {
    case TEST_ONEOF_NOT_SET:
      break;
      case kI32:
        _impl_.test_oneof_.i32_ = from._impl_.test_oneof_.i32_;
        break;
      case kI64:
        _impl_.test_oneof_.i64_ = from._impl_.test_oneof_.i64_;
        break;
      case kF32:
        _impl_.test_oneof_.f32_ = from._impl_.test_oneof_.f32_;
        break;
      case kF64:
        _impl_.test_oneof_.f64_ = from._impl_.test_oneof_.f64_;
        break;
  }

  // @@protoc_insertion_point(copy_constructor:chkpt.Value)
}
inline PROTOBUF_NDEBUG_INLINE Value::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : test_oneof_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Value::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
Value::~Value() {
  // @@protoc_insertion_point(destructor:chkpt.Value)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Value::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_test_oneof()) {
    clear_test_oneof();
  }
  _impl_.~Impl_();
}

void Value::clear_test_oneof() {
// @@protoc_insertion_point(one_of_clear_start:chkpt.Value)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (test_oneof_case()) {
    case kI32: {
      // No need to clear
      break;
    }
    case kI64: {
      // No need to clear
      break;
    }
    case kF32: {
      // No need to clear
      break;
    }
    case kF64: {
      // No need to clear
      break;
    }
    case TEST_ONEOF_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = TEST_ONEOF_NOT_SET;
}


PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Value::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Value_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Value::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Value>(),
            ::google::protobuf::Message::GetNewImpl<Value>(),
            ::google::protobuf::Message::GetClearImpl<Value>(), &Value::ByteSizeLong,
                &Value::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Value, _impl_._cached_size_),
            false,
        },
        &Value::kDescriptorMethods,
        &descriptor_table_protobuf_2fchkpt_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Value::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 5, 0, 0, 2> Value::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chkpt::Value>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .chkpt.Type.Enum type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Value, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Value, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .chkpt.Type.Enum type = 1;
    {PROTOBUF_FIELD_OFFSET(Value, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 i32 = 2;
    {PROTOBUF_FIELD_OFFSET(Value, _impl_.test_oneof_.i32_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // int64 i64 = 3;
    {PROTOBUF_FIELD_OFFSET(Value, _impl_.test_oneof_.i64_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // float f32 = 4;
    {PROTOBUF_FIELD_OFFSET(Value, _impl_.test_oneof_.f32_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kFloat)},
    // double f64 = 5;
    {PROTOBUF_FIELD_OFFSET(Value, _impl_.test_oneof_.f64_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Value::Clear() {
// @@protoc_insertion_point(message_clear_start:chkpt.Value)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  clear_test_oneof();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Value::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Value& this_ = static_cast<const Value&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Value::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Value& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chkpt.Value)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .chkpt.Type.Enum type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          switch (this_.test_oneof_case()) {
            case kI32: {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<2>(
                      stream, this_._internal_i32(), target);
              break;
            }
            case kI64: {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt64ToArrayWithField<3>(
                      stream, this_._internal_i64(), target);
              break;
            }
            case kF32: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFloatToArray(
                  4, this_._internal_f32(), target);
              break;
            }
            case kF64: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                  5, this_._internal_f64(), target);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chkpt.Value)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Value::ByteSizeLong(const MessageLite& base) {
          const Value& this_ = static_cast<const Value&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Value::ByteSizeLong() const {
          const Value& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chkpt.Value)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .chkpt.Type.Enum type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          switch (this_.test_oneof_case()) {
            // int32 i32 = 2;
            case kI32: {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_i32());
              break;
            }
            // int64 i64 = 3;
            case kI64: {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_i64());
              break;
            }
            // float f32 = 4;
            case kF32: {
              total_size += 5;
              break;
            }
            // double f64 = 5;
            case kF64: {
              total_size += 9;
              break;
            }
            case TEST_ONEOF_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Value::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Value*>(&to_msg);
  auto& from = static_cast<const Value&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chkpt.Value)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_test_oneof();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kI32: {
        _this->_impl_.test_oneof_.i32_ = from._impl_.test_oneof_.i32_;
        break;
      }
      case kI64: {
        _this->_impl_.test_oneof_.i64_ = from._impl_.test_oneof_.i64_;
        break;
      }
      case kF32: {
        _this->_impl_.test_oneof_.f32_ = from._impl_.test_oneof_.f32_;
        break;
      }
      case kF64: {
        _this->_impl_.test_oneof_.f64_ = from._impl_.test_oneof_.f64_;
        break;
      }
      case TEST_ONEOF_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Value::CopyFrom(const Value& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chkpt.Value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Value::InternalSwap(Value* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_.test_oneof_, other->_impl_.test_oneof_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Value::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Frame::_Internal {
 public:
};

Frame::Frame(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chkpt.Frame)
}
inline PROTOBUF_NDEBUG_INLINE Frame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chkpt::Frame& from_msg)
      : locals_{visibility, arena, from.locals_},
        stack_{visibility, arena, from.stack_},
        _cached_size_{0} {}

Frame::Frame(
    ::google::protobuf::Arena* arena,
    const Frame& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Frame* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fn_idx_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, fn_idx_),
           offsetof(Impl_, pc_) -
               offsetof(Impl_, fn_idx_) +
               sizeof(Impl_::pc_));

  // @@protoc_insertion_point(copy_constructor:chkpt.Frame)
}
inline PROTOBUF_NDEBUG_INLINE Frame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : locals_{visibility, arena},
        stack_{visibility, arena},
        _cached_size_{0} {}

inline void Frame::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fn_idx_),
           0,
           offsetof(Impl_, pc_) -
               offsetof(Impl_, fn_idx_) +
               sizeof(Impl_::pc_));
}
Frame::~Frame() {
  // @@protoc_insertion_point(destructor:chkpt.Frame)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Frame::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Frame::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Frame_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Frame::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Frame>(),
            ::google::protobuf::Message::GetNewImpl<Frame>(),
            ::google::protobuf::Message::GetClearImpl<Frame>(), &Frame::ByteSizeLong,
                &Frame::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Frame, _impl_._cached_size_),
            false,
        },
        &Frame::kDescriptorMethods,
        &descriptor_table_protobuf_2fchkpt_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Frame::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 0, 2> Frame::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chkpt::Frame>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .chkpt.Value stack = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 1, PROTOBUF_FIELD_OFFSET(Frame, _impl_.stack_)}},
    // int32 fn_idx = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Frame, _impl_.fn_idx_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Frame, _impl_.fn_idx_)}},
    // int32 pc = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Frame, _impl_.pc_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Frame, _impl_.pc_)}},
    // repeated .chkpt.Value locals = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Frame, _impl_.locals_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 fn_idx = 1;
    {PROTOBUF_FIELD_OFFSET(Frame, _impl_.fn_idx_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 pc = 2;
    {PROTOBUF_FIELD_OFFSET(Frame, _impl_.pc_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .chkpt.Value locals = 3;
    {PROTOBUF_FIELD_OFFSET(Frame, _impl_.locals_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .chkpt.Value stack = 4;
    {PROTOBUF_FIELD_OFFSET(Frame, _impl_.stack_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::chkpt::Value>()},
    {::_pbi::TcParser::GetTable<::chkpt::Value>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Frame::Clear() {
// @@protoc_insertion_point(message_clear_start:chkpt.Frame)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.locals_.Clear();
  _impl_.stack_.Clear();
  ::memset(&_impl_.fn_idx_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.pc_) -
      reinterpret_cast<char*>(&_impl_.fn_idx_)) + sizeof(_impl_.pc_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Frame::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Frame& this_ = static_cast<const Frame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Frame::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Frame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chkpt.Frame)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 fn_idx = 1;
          if (this_._internal_fn_idx() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_fn_idx(), target);
          }

          // int32 pc = 2;
          if (this_._internal_pc() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_pc(), target);
          }

          // repeated .chkpt.Value locals = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_locals_size());
               i < n; i++) {
            const auto& repfield = this_._internal_locals().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .chkpt.Value stack = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_stack_size());
               i < n; i++) {
            const auto& repfield = this_._internal_stack().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chkpt.Frame)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Frame::ByteSizeLong(const MessageLite& base) {
          const Frame& this_ = static_cast<const Frame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Frame::ByteSizeLong() const {
          const Frame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chkpt.Frame)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .chkpt.Value locals = 3;
             {
              total_size += 1UL * this_._internal_locals_size();
              for (const auto& msg : this_._internal_locals()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .chkpt.Value stack = 4;
             {
              total_size += 1UL * this_._internal_stack_size();
              for (const auto& msg : this_._internal_stack()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // int32 fn_idx = 1;
            if (this_._internal_fn_idx() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_fn_idx());
            }
            // int32 pc = 2;
            if (this_._internal_pc() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_pc());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Frame::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Frame*>(&to_msg);
  auto& from = static_cast<const Frame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chkpt.Frame)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_locals()->MergeFrom(
      from._internal_locals());
  _this->_internal_mutable_stack()->MergeFrom(
      from._internal_stack());
  if (from._internal_fn_idx() != 0) {
    _this->_impl_.fn_idx_ = from._impl_.fn_idx_;
  }
  if (from._internal_pc() != 0) {
    _this->_impl_.pc_ = from._impl_.pc_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Frame::CopyFrom(const Frame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chkpt.Frame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Frame::InternalSwap(Frame* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.locals_.InternalSwap(&other->_impl_.locals_);
  _impl_.stack_.InternalSwap(&other->_impl_.stack_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Frame, _impl_.pc_)
      + sizeof(Frame::_impl_.pc_)
      - PROTOBUF_FIELD_OFFSET(Frame, _impl_.fn_idx_)>(
          reinterpret_cast<char*>(&_impl_.fn_idx_),
          reinterpret_cast<char*>(&other->_impl_.fn_idx_));
}

::google::protobuf::Metadata Frame::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Checkpoint::_Internal {
 public:
};

Checkpoint::Checkpoint(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chkpt.Checkpoint)
}
inline PROTOBUF_NDEBUG_INLINE Checkpoint::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chkpt::Checkpoint& from_msg)
      : frames_{visibility, arena, from.frames_},
        globals_{visibility, arena, from.globals_},
        table_{visibility, arena, from.table_},
        _table_cached_byte_size_{0},
        memory_lz4_(arena, from.memory_lz4_),
        _cached_size_{0} {}

Checkpoint::Checkpoint(
    ::google::protobuf::Arena* arena,
    const Checkpoint& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Checkpoint* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.memory_size_ = from._impl_.memory_size_;

  // @@protoc_insertion_point(copy_constructor:chkpt.Checkpoint)
}
inline PROTOBUF_NDEBUG_INLINE Checkpoint::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : frames_{visibility, arena},
        globals_{visibility, arena},
        table_{visibility, arena},
        _table_cached_byte_size_{0},
        memory_lz4_(arena),
        _cached_size_{0} {}

inline void Checkpoint::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.memory_size_ = {};
}
Checkpoint::~Checkpoint() {
  // @@protoc_insertion_point(destructor:chkpt.Checkpoint)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Checkpoint::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.memory_lz4_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Checkpoint::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Checkpoint_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Checkpoint::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Checkpoint>(),
            ::google::protobuf::Message::GetNewImpl<Checkpoint>(),
            ::google::protobuf::Message::GetClearImpl<Checkpoint>(), &Checkpoint::ByteSizeLong,
                &Checkpoint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_._cached_size_),
            false,
        },
        &Checkpoint::kDescriptorMethods,
        &descriptor_table_protobuf_2fchkpt_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Checkpoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 0, 2> Checkpoint::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chkpt::Checkpoint>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .chkpt.Frame frames = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.frames_)}},
    // repeated .chkpt.Value globals = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.globals_)}},
    // repeated int32 table = 3;
    {::_pbi::TcParser::FastV32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.table_)}},
    // int32 memory_size = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Checkpoint, _impl_.memory_size_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.memory_size_)}},
    // bytes memory_lz4 = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.memory_lz4_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .chkpt.Frame frames = 1;
    {PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.frames_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .chkpt.Value globals = 2;
    {PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.globals_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated int32 table = 3;
    {PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.table_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // int32 memory_size = 4;
    {PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.memory_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bytes memory_lz4 = 5;
    {PROTOBUF_FIELD_OFFSET(Checkpoint, _impl_.memory_lz4_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::chkpt::Frame>()},
    {::_pbi::TcParser::GetTable<::chkpt::Value>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Checkpoint::Clear() {
// @@protoc_insertion_point(message_clear_start:chkpt.Checkpoint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.frames_.Clear();
  _impl_.globals_.Clear();
  _impl_.table_.Clear();
  _impl_.memory_lz4_.ClearToEmpty();
  _impl_.memory_size_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Checkpoint::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Checkpoint& this_ = static_cast<const Checkpoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Checkpoint::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Checkpoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chkpt.Checkpoint)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .chkpt.Frame frames = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_frames_size());
               i < n; i++) {
            const auto& repfield = this_._internal_frames().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .chkpt.Value globals = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_globals_size());
               i < n; i++) {
            const auto& repfield = this_._internal_globals().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated int32 table = 3;
          {
            int byte_size = this_._impl_._table_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  3, this_._internal_table(), byte_size, target);
            }
          }

          // int32 memory_size = 4;
          if (this_._internal_memory_size() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_memory_size(), target);
          }

          // bytes memory_lz4 = 5;
          if (!this_._internal_memory_lz4().empty()) {
            const std::string& _s = this_._internal_memory_lz4();
            target = stream->WriteBytesMaybeAliased(5, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chkpt.Checkpoint)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Checkpoint::ByteSizeLong(const MessageLite& base) {
          const Checkpoint& this_ = static_cast<const Checkpoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Checkpoint::ByteSizeLong() const {
          const Checkpoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chkpt.Checkpoint)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .chkpt.Frame frames = 1;
             {
              total_size += 1UL * this_._internal_frames_size();
              for (const auto& msg : this_._internal_frames()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .chkpt.Value globals = 2;
             {
              total_size += 1UL * this_._internal_globals_size();
              for (const auto& msg : this_._internal_globals()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated int32 table = 3;
             {
              std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
                  this_._internal_table())
              ;
              this_._impl_._table_cached_byte_size_.Set(
                  ::_pbi::ToCachedSize(data_size));
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size))
              ;
              total_size += tag_size + data_size;
            }
          }
           {
            // bytes memory_lz4 = 5;
            if (!this_._internal_memory_lz4().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_memory_lz4());
            }
            // int32 memory_size = 4;
            if (this_._internal_memory_size() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_memory_size());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Checkpoint::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Checkpoint*>(&to_msg);
  auto& from = static_cast<const Checkpoint&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chkpt.Checkpoint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_frames()->MergeFrom(
      from._internal_frames());
  _this->_internal_mutable_globals()->MergeFrom(
      from._internal_globals());
  _this->_internal_mutable_table()->MergeFrom(from._internal_table());
  if (!from._internal_memory_lz4().empty()) {
    _this->_internal_set_memory_lz4(from._internal_memory_lz4());
  }
  if (from._internal_memory_size() != 0) {
    _this->_impl_.memory_size_ = from._impl_.memory_size_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Checkpoint::CopyFrom(const Checkpoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chkpt.Checkpoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Checkpoint::InternalSwap(Checkpoint* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.frames_.InternalSwap(&other->_impl_.frames_);
  _impl_.globals_.InternalSwap(&other->_impl_.globals_);
  _impl_.table_.InternalSwap(&other->_impl_.table_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.memory_lz4_, &other->_impl_.memory_lz4_, arena);
        swap(_impl_.memory_size_, other->_impl_.memory_size_);
}

::google::protobuf::Metadata Checkpoint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace chkpt
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_protobuf_2fchkpt_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
